### ISSUE TITLE
tests not running on NodeJS v18

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/stopword#294]
```console
  Uncaught exception in test/test.js

  TypeError: Cannot destructure property 'payload' of 'sourceMap' as it is null.

  › file:///Users/eklem/github_modules/stopword/node_modules/mem/dist/index.js:42:27
  › file:///Users/eklem/github_modules/stopword/node_modules/mem/dist/index.js:42:27

  ✔ passes serially
  ✖ Internal error when running test/test.js
  TypeError: Cannot destructure property 'payload' of 'sourceMap' as it is null.
  TypeError: Cannot destructure property 'payload' of 'sourceMap' as it is null.
      at file:///Users/eklem/github_modules/stopword/node_modules/ava/lib/snapshot-manager.js:398:9
      at file:///Users/eklem/github_modules/stopword/node_modules/mem/dist/index.js:42:27
      at mem.cacheKey.file.file (file:///Users/eklem/github_modules/stopword/node_modules/ava/lib/snapshot-manager.js:409:31)
      at file:///Users/eklem/github_modules/stopword/node_modules/mem/dist/index.js:42:27
      at determineSnapshotPaths (file:///Users/eklem/github_modules/stopword/node_modules/ava/lib/snapshot-manager.js:428:14)
      at load (file:///Users/eklem/github_modules/stopword/node_modules/ava/lib/snapshot-manager.js:468:16)
      at get snapshots [as snapshots] (file:///Users/eklem/github_modules/stopword/node_modules/ava/lib/runner.js:204:21)
      at Runner.saveSnapshotState (file:///Users/eklem/github_modules/stopword/node_modules/ava/lib/runner.js:228:36)
      at file:///Users/eklem/github_modules/stopword/node_modules/ava/lib/worker/base.js:84:40
      at /Users/eklem/github_modules/stopword/node_modules/emittery/index.js:319:13


  ✖ test/test.js exited with a non-zero exit code: 1
  ─

  1 test passed
  1 uncaught exception
```

Seems to be an AvaJS - NodeJS v18 problem...

**Comment by eklem** [comment]
The issue seems to be Node v18.8.0: https://github.com/nodejs/node/issues/44391

Tried v18.7.0 and that worked, so just wait for 18.9.0 ?

**Comment by eklem** [comment]
Batr needs to be updated with latest AvaJS version (4.3.3) to work with NodeJS v18.8.0.

**Comment by eklem** [comment]
Fixed with https://github.com/fergiemcdowall/stopword/commit/05cbfdcffdfd90e81b13f94951ab9981c0cf1b82
